language: python

python:
  - "3.5"

services:
  - docker

before_install:
  - docker build -t fss .
  - docker images
  - docker run -d -p 5000:5000 fss
  - docker ps -a

script:
  - docker ps | grep -q fss
