language: python

python:
  - "3.5"

services:
  - docker

install:
  - docker build -t fss .
  - docker images
  - docker run -d -p 5000:5000 fss
  - docker ps -a

before_script:
  - pip3 install -r travis_requirements.txt

script:
  - docker ps | grep -q fss
  - pytest -v ./tests
